### ISSUE TITLE
Export Evernote Joy of Coding episode agendas

### ISSUE THREAD

**Issue by dannycolin** [mikeconley/joy-of-coding-episode-guide#105]
Hi @mikeconley, 

Would it be possible for you to share the whole Joy of Coding agenda book from your Evernote? This way I could do a batch export of them. After that, I'll convert them in markdown and add them to the episode guide. 

I'll also add the instructions in CONTRIBUTING.md on how to export an agenda so any contributor adding a new episode to the guide will be able to also include the agenda that goes with it.

**Comment by mikeconley** [comment]
Sure! I've just put them into the most recent commit.

**Comment by dannycolin** [comment]
Fixed via [0c04c3f](https://github.com/mikeconley/joy-of-coding-episode-guide/commit/0c04c3f1b82fd3598026609a706232ae210e6e2d)
