### ISSUE TITLE
Use DeepSpeech trained voice model to create automated transcriptions of videos that can be indexed and searched

### ISSUE THREAD

**Issue by mikeconley** [mikeconley/joy-of-coding-episode-guide#15]
DeepSpeech is a project by Mozilla to do Speech-To-Text analysis in an open-source way, and Mozilla has recently released a trained speech model that apparently does pretty well. 

[Here's a link to the model.](https://github.com/mozilla/DeepSpeech/releases/tag/v0.1.0)

One idea is to go through all of the past recordings, extract the audio, and run DeepSpeech over it to produce an automated transcription. Bonus points if it can timecode it for closed captioning!

Then, we can index those transcriptions and people (like me too!) can search them.

**Comment by mikeconley** [comment]
[Relevant blog post](https://www.phpied.com/taking-mozillas-deepspeech-for-a-spin/)

**Comment by JohnstonCode** [comment]
This is harder than expected to run.

Two and a half hours in "Segmentation fault (core dumped)"

**Comment by JohnstonCode** [comment]
Does seem to work for a [smaller video](https://www.youtube.com/watch?v=pJY0mBWHPw4) this is the [output](https://gist.github.com/JohnstonCode/2995dc7324ccd4a725228fa1233fc85b).

Possibly a memory issue. 12GB might not be enough.

**Comment by JohnstonCode** [comment]
@mikeconley If you are still after transcripts youtube's closed captions are pretty spot on.

**Comment by mikeconley** [comment]
Hey folks, finally had a chance to hack on this this weekend. I've dumped a script into utils/ called "Adso" that does the work of downloading a video, extracting the audio, and using DeepSpeech to generate VTT files.

I've started to put the videos and captions up on [Amara.org](https://amara.org/en/profiles/videos/mconley/). If people want to contribute corrections to the captions (because DeepSpeech sure has spirit but sometimes it gets things dead wrong), please do.

I'll put a more formal call out for contribution in an upcoming episode.
